### ISSUE TITLE
Screen saver not picking up new content in Google Photos directory

### ISSUE THREAD

**Issue by msmallcombe** [opus1269/photo-screen-saver#18]
I'd like to use the photo screen saver to display KPI dashboards on a Chromebit. When I upload KPI screenshots to the Google Photos directory the screen saver doesn't display the new images.

**Comment by opus1269** [comment]
The screensaver reloads the the albums photo urls once a day based on an alarm that has a variable time, and each time you start Chrome from a full exit.

It does not know when photos are added in Google Photos.
